// <auto-generated />
using giftideas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace giftideas.Migrations
{
    [DbContext(typeof(GiftIdeasContext))]
    partial class GiftIdeasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("giftideas.Models.GiftIdea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<string>("GiftDescription");

                    b.Property<long>("HolidayId");

                    b.Property<long>("RecipientId");

                    b.HasKey("Id");

                    b.ToTable("GiftIdeas");
                });

            modelBuilder.Entity("giftideas.Models.Holiday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<int>("Day");

                    b.Property<int>("Month");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("giftideas.Models.Recipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
